AlumniPortal/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('HomePage.urls')),
    path('post/',include('posts.urls')),
    path('alumni/',include('alumni.urls')),
    path('gallery/',include('gallery.urls')),
    path('community/',include('community.urls')),
    path('register/',include('registration.urls')),
    path('authentication/', include('authentication.urls')),
    path('pages/', include('pages.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
# urlpatterns += staticfiles_urlpatterns()

alumni/urls.py
# Django
from django.urls import path

# local Django
from alumni import views
from .views import (AlumniUpdateView, ProfileView)

app_name = 'alumni'

urlpatterns = [
    path('profile/<int:alumni_id>',ProfileView.as_view(),name='profile'),
    path('edit/<int:alumni_id>',AlumniUpdateView.as_view(),name='edit'),
]

community/urls.py
from django.urls import path
from .views import CommunityView

app_name='community'

urlpatterns = [
    path('',CommunityView.as_view(),name='community_page'),
]

pages/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from .views import AboutUs,ContactUs,NotAllowed,RegistrationEmailError

app_name='pages'

urlpatterns = [
    path('about_us/', AboutUs, name='about_us'),
    path('contact_us/', ContactUs, name='contact_us'),
    path('error/', NotAllowed, name='not_allowed'),
    path('server_error/', RegistrationEmailError, name='RegistrationEmailError')
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
# urlpatterns += staticfiles_urlpatterns()

community/models.py
from django.db import models

# Create your models here.

community/views.py
from alumni.models import Alumni
from django.views import generic
from django.db.models import Q


class CommunityView(generic.ListView):
    template_name = 'community/community.html'

    def get_queryset(self):
        request = self.request
        queryset_list = Alumni.objects.all()
        query = request.GET.get('q')
        if query:
            queryset_list = queryset_list.filter(
                Q(first_name__icontains=query) |
                Q(last_name__icontains=query) |
                Q(area_of_expertise__icontains=query) |
                Q(permanent_address__icontains=query) |
                Q(email__icontains=query)
            ).distinct()
        return queryset_list

community/templates/community/community.html
{% extends "AlumniPortal/base.html" %}
{% load static %}
{% load i18n %}


{% block content %}

  <div class="container">
  <br>
    <div class="container">
        <form method = 'GET' action = "">
            <input type = "text" name = "q" placeholder="searchcommunity" value = "{{ request.GET.q }}"/>
            <input type = "submit" value = "search" />
        </form>
    </div>
    <div class="row">
            {% for al in object_list %}
                    {% if al.user.is_active %}
                    <div class="col-md-3">
                        <div class="grey-box-icon">
                            <div class="icon-box-top grey-box-icon-pos">
                                <img src="{{ al.profile_pic.url }}" alt="" height="125" width="200" />
                            </div><!--icon box top -->
                            <h4>{{ al.first_name }} {{ al.last_name }}</h4>
                            <p><a {% if user.is_authenticated %}href="{% url 'alumni:profile' al.id %}"{% else %}href="{% url 'pages:not_allowed' %}"{% endif %}><em>Know More</em></a></p>
                        </div><!--grey box -->
                    </div><!--/span3-->
                    {% endif %}
            {% endfor %}
        </div>
    </div>
{% endblock %}