AlumniPortal/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('HomePage.urls')),
    path('post/',include('posts.urls')),
    path('alumni/',include('alumni.urls')),
    path('gallery/',include('gallery.urls')),
    path('community/',include('community.urls')),
    path('register/',include('registration.urls')),
    path('authentication/', include('authentication.urls')),
    path('pages/', include('pages.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
# urlpatterns += staticfiles_urlpatterns()

authentication/urls.py
# Django
from django.urls import path
from django.contrib.auth.views import (LoginView, LogoutView,
                                       PasswordResetView,
                                       PasswordResetDoneView,
                                       PasswordResetConfirmView,
                                       PasswordResetCompleteView,
                                       PasswordChangeView,
                                       PasswordChangeDoneView)

# local Django
from authentication import views
from authentication.views import anonymous_required
from authentication.forms import EmailValidationOnForgotPassword
from AlumniPortal import settings

app_name = 'authentication'

urlpatterns = [
    path('', views.index, name='index'),
    path('login/',
         anonymous_required(
             LoginView.as_view(
                 template_name='authentication/login.html'
             )
         ),
         name='login_process'),
    path('logout/',
         LogoutView.as_view(template_name='HomePage/HomePage.html'),
         name='logout_process'),
    path('password_reset/',
         PasswordResetView.as_view(email_template_name='authentication/password_reset_email.html',
                                   template_name='authentication/password_reset_form.html',
                                   success_url='done/',
                                   form_class=EmailValidationOnForgotPassword,
                                   subject_template_name='authentication/password_reset_subject.txt',
                                   from_email=settings.EMAIL_HOST_USER
                                   ),
         name='password_reset'),
    path('password_reset/done/',
         PasswordResetDoneView.as_view(
             template_name='authentication/password_reset_done.html'
         ),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(
             template_name= 'authentication/password_change_form.html',
             success_url='/authentication/reset/complete/'
         ),
         name='password_reset_confirm'),
    path('reset/complete/',
         PasswordResetCompleteView.as_view(
             template_name='authentication/password_reset_complete.html'
         ),
         name='password_reset_complete'
         ),
    path('change-password/',
         PasswordChangeView.as_view(success_url='done/'),
         name='password_change'),
    path('change-password/done/',
         PasswordChangeDoneView.as_view(
             template_name='authentication/password_change_done.html'
         ),
         name='password_change_done'),
]

pages/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from .views import AboutUs,ContactUs,NotAllowed,RegistrationEmailError

app_name='pages'

urlpatterns = [
    path('about_us/', AboutUs, name='about_us'),
    path('contact_us/', ContactUs, name='contact_us'),
    path('error/', NotAllowed, name='not_allowed'),
    path('server_error/', RegistrationEmailError, name='RegistrationEmailError')
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
# urlpatterns += staticfiles_urlpatterns()

registration/urls.py
from django.urls import path
from .views import AlumniSignupView
from registration import  views
from django.conf.urls import include, url
app_name = 'registration'

urlpatterns = [
    path('',AlumniSignupView.as_view(),name='signup_alumni'),
    url(r'^signup/activate/(?P<uidb64>[0-9A-Za-z_\-]+)/'r'(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',views.activate,name='activate'),
]

pages/templates/pages/about_us.html
{% extends "AlumniPortal/base.html" %}
{% load static %}
{% load i18n %}


{% block content %}
    <div class="row">
<div class="col-lg-12">
	<div id="flash-messages">
							</div>
	<div id="ph">
				<div class="page-header">
		<div class="page-header-links">
						</div>
				<h1 class="c1 color-font" title="About Us"><a href="">
		About Us</a>
		<span class="hidden-xs hidden-sm"></span>
		</h1>
		</div>
					</div>
		<div class="row no-pad content-box-innner border-top color-border c1">
		<div id="sl" class="col-md-12">
					</div>
		<div id="sc" class="col-md-12">
						<div class="visible-lg visible-md"><div id="nav-user-page">
	</div></div>		</div>
		<div id="dc" class="col-md-10 col-md-push-1">
			<div class="row no-pad">
				<div id="ch" class="col-md-12">
									</div>
			</div>
			<div class="row no-pad">
				<div id="ic" class="col-md-12">
									</div>
				<div id="cc" class="col-md-12">
										<div class="post">
<p style="text-align: justify;">Established in <strong>2018</strong> by the joint efforts of faculty and students of <strong>IIIT Vadodara</strong>, a network which aims at strengthening the bond of alumni with the current scholars, faculty and the campus. The body now runs with the support of alumni all across the globe. Dynamically changing and rapidly growing, the community has brought diverse transformations for the community and anticipates in manifolds its attempts with time.</p>
<h3 style="text-align: justify;">Objectives:</h3>
<ul>
<li style="text-align: justify;">The mission of <strong>Alumni Association</strong> is to provide a platform to connect the alumni and the alma mater in a synergetic relationship:</li>
<ul>
<li>To engage the alumni to proffer supervision to lead the organization forward</li>
<li>To ensure the institute’s core values and missions.</li>
<li>To provide an environment for fund raising activities.</li>
<li>To launch initiatives for inter and intra-networking among the alumni and the alma mater.</li>
<li>Institutional brand building.</li>
<li>To connect and celebrate the achievements of the alumni, faculty, staff and students</li>
<li>Provide active support and guidance through mentorship programs.</li>
</ul>
</ul>
<ul>
<li><strong>Alumni Affairs Committee <br></strong></li>
<ul>
<li><strong><a href="#" target="_blank">Past Committee</a></strong></li>
</ul>
<ul>
<li>Dr. ABC <strong>[Chair]</strong></li>
<li>Dr. DEF <strong>[Past Chair]</strong></li>
<li>Dr. GHI <strong>[Co-Chair]</strong></li>
</ul>
<ul>
<li>Dr. JKL <strong>[Member]</strong></li>
<li>Ms. MNO <strong>[ Member Convener]</strong></li>
</ul>
</ul>
<h3>Alumni Cell:</h3>
<p><strong><a href="#" target="_blank">Past members</a></strong></p>
<p><strong>Current members:</strong></p>
<ul>
<li><strong>Coordinator</strong></li>
</ul>
<ul>
<ul>
<li><a href="#">PQR</a></li>
</ul>
</ul>
<ul>
<li><strong>Department Representatives Team</strong></li>
</ul>
<ul>
<ul>
<li><strong><a href="#">STU</a></strong></li>
<li>Anirudh Dahiya</li>
<li><a href="#">VWX</a></li>
</ul>
</ul>
<ul>
<li><strong>Logistics</strong>&nbsp;&nbsp;
<ul>
<li><strong><a href="#">ZYX</a></strong></li>
<li><a href="#">VUT</a></li>
<li>SRQ</li>
</ul>
</li>
</ul>
<ul>
<li><strong>Public Relations and Reports</strong>
<ul>
<li><strong><a href="#" target="_blank">PON</a></strong></li>
<li><span style="font-weight: 400;">MLK</span></li>
<li><span style="font-weight: 400;">JIH</span></li>
</ul>
</li>
<li><strong>Social Media and Outreach</strong>
<ul>
<li><strong><a href="#">GFE</a></strong></li>
<li><a href="#">DCB</a></li>
<li>AZY</li>
</ul>
</li>
</ul>
<p>&nbsp;</p>
<p><strong>Note:</strong> In bolds - POCs for the respective teams.</p></div>
				</div>
			</div>
		</div>
	</div>
</div>
</div>
{% endblock %}

pages/templates/pages/contact_us.html
{% extends "AlumniPortal/base.html" %}
{% load static %}
{% load i18n %}


{% block content %}
    <h1>Contact us Page</h1>
    <h2>Redirect to <a href="http://www.iiitvadodara.ac.in/">IIITV </a>page</h2>
{% endblock %}

pages/templates/pages/fill_proper_email.html
{% extends "AlumniPortal/base.html" %}
{% load static %}
{% load i18n %}


{% block content %}
    <h1></h1>
{% endblock %}

pages/templates/pages/not_allowed.html
{% extends "AlumniPortal/base.html" %}
{% load static %}
{% load i18n %}


{% block content %}
    <h1>You have to <a href="{% url 'authentication:login_process' %}">login </a>first, to access the page.</h1>
{% endblock %}

pages/templates/pages/registration_email_error.html
{% extends "AlumniPortal/base.html" %}
{% load static %}
{% load i18n %}


{% block content %}
    <h1>Sorry, but some server problems. You can try again at <a href="{% url 'registration:signup_alumni' %}">here.</a></h1>
{% endblock %}

pages/templates/pages/user_is_logged_in.html
{% extends "AlumniPortal/base.html" %}
{% load static %}
{% load i18n %}


{% block content %}
    <h1>You are already logged in, to make a new acccount <a href="{% url 'authentication:logout_process' %}">logout </a>first.</h1>
{% endblock %}