AlumniPortal/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('HomePage.urls')),
    path('post/',include('posts.urls')),
    path('alumni/',include('alumni.urls')),
    path('gallery/',include('gallery.urls')),
    path('community/',include('community.urls')),
    path('register/',include('registration.urls')),
    path('authentication/', include('authentication.urls')),
    path('pages/', include('pages.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
# urlpatterns += staticfiles_urlpatterns()

HomePage/urls.py
from django.urls import path
from .views import HomePage

app_name = 'HomePage'

urlpatterns = [
    path('',HomePage.as_view(),name='homepage'),
]

authentication/urls.py
# Django
from django.urls import path
from django.contrib.auth.views import (LoginView, LogoutView,
                                       PasswordResetView,
                                       PasswordResetDoneView,
                                       PasswordResetConfirmView,
                                       PasswordResetCompleteView,
                                       PasswordChangeView,
                                       PasswordChangeDoneView)

# local Django
from authentication import views
from authentication.views import anonymous_required
from authentication.forms import EmailValidationOnForgotPassword
from AlumniPortal import settings

app_name = 'authentication'

urlpatterns = [
    path('', views.index, name='index'),
    path('login/',
         anonymous_required(
             LoginView.as_view(
                 template_name='authentication/login.html'
             )
         ),
         name='login_process'),
    path('logout/',
         LogoutView.as_view(template_name='HomePage/HomePage.html'),
         name='logout_process'),
    path('password_reset/',
         PasswordResetView.as_view(email_template_name='authentication/password_reset_email.html',
                                   template_name='authentication/password_reset_form.html',
                                   success_url='done/',
                                   form_class=EmailValidationOnForgotPassword,
                                   subject_template_name='authentication/password_reset_subject.txt',
                                   from_email=settings.EMAIL_HOST_USER
                                   ),
         name='password_reset'),
    path('password_reset/done/',
         PasswordResetDoneView.as_view(
             template_name='authentication/password_reset_done.html'
         ),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(
             template_name= 'authentication/password_change_form.html',
             success_url='/authentication/reset/complete/'
         ),
         name='password_reset_confirm'),
    path('reset/complete/',
         PasswordResetCompleteView.as_view(
             template_name='authentication/password_reset_complete.html'
         ),
         name='password_reset_complete'
         ),
    path('change-password/',
         PasswordChangeView.as_view(success_url='done/'),
         name='password_change'),
    path('change-password/done/',
         PasswordChangeDoneView.as_view(
             template_name='authentication/password_change_done.html'
         ),
         name='password_change_done'),
]

pages/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from .views import AboutUs,ContactUs,NotAllowed,RegistrationEmailError

app_name='pages'

urlpatterns = [
    path('about_us/', AboutUs, name='about_us'),
    path('contact_us/', ContactUs, name='contact_us'),
    path('error/', NotAllowed, name='not_allowed'),
    path('server_error/', RegistrationEmailError, name='RegistrationEmailError')
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
# urlpatterns += staticfiles_urlpatterns()

posts/urls.py
from django.urls import path

from posts import views
app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('submit/', views.submit, name='submit'),
    path('<int:id>', views.details, name='details'),
    path('<int:id>/upvote', views.upvote, name='upvote'),
    path('<int:id>/downvote', views.downvote, name='downvote'),
    path('<int:post_id>/comments/<int:node_id>/upvote', views.comment_upvote, name='comment_upvote'),
    path('<int:post_id>/comments/<int:node_id>/downvote', views.comment_downvote, name='comment_downvote'),
    path('<int:post_id>/comments/reply/<int:parent_id>', views.comment_reply, name='comment_reply'),
]

posts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from mptt.models import MPTTModel, TreeForeignKey
from urllib.parse import urlparse
from datetime import datetime


class Post(models.Model):
    title = models.CharField(max_length=200)
    user = models.ForeignKey(User, on_delete='CASCADE')
    date = models.DateTimeField(auto_now_add=True)
    link = models.URLField(max_length=600, blank=True)
    text = models.TextField(blank=True)
    image = models.ImageField(blank=True, null=True, upload_to='posts')
    def score(self):
        return Vote.objects.filter(post=self, upvote=True).count() - Vote.objects.filter(post=self,
                                                                                         upvote=False).count()

    def comments_count(self):
        return Comment.objects.filter(post=self).count()

    def get_domain(self):
        return urlparse(self.link).netloc

    def get_absolute_url(self):
        return reverse('posts:details', args=[str(self.pk)])

    def __unicode__(self):
        return self.title


class Vote(models.Model):
    voter = models.ForeignKey(User, on_delete='CASCADE')
    post = models.ForeignKey(Post, on_delete='CASCADE')
    upvote = models.BooleanField()

    def __unicode__(self):
        return "%s upvoted %s" % (self.voter.username, self.post.title)


class Comment(MPTTModel):
    """ Threaded comments for posts """
    post = models.ForeignKey(Post, on_delete='CASCADE')
    author = models.ForeignKey(User, on_delete='CASCADE')
    comment = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    # a link to comment that is being replied, if one exists
    parent = TreeForeignKey('self', null=True, blank=True, related_name='children', on_delete='CASCADE')

    def score(self):
        return CommentVote.objects.filter(comment=self, upvote=True).count() - CommentVote.objects.filter(comment=self,
                                                                                                          upvote=False).count()

    class MPTTMeta:
        order_insertion_by = ['date']

    def save(self, *args, **kwargs):
        if not self.date:
            self.date = datetime.now()
        super(Comment, self).save(*args, **kwargs)

    def __unicode__(self):
        return "%s comment on %s" % (self.author.username, self.post)


class CommentVote(models.Model):
    voter = models.ForeignKey(User, on_delete='CASCADE')
    comment = models.ForeignKey(Comment, on_delete='CASCADE')
    upvote = models.BooleanField()

    def __unicode__(self):
        return "%s upvoted %s" % (self.voter.username, self.comment)

posts/views.py
from django.shortcuts import  render, redirect
from django.contrib.auth.decorators import login_required
from posts.models import *
from django.forms import ModelForm
from django import forms
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Q
from .models import Post
from itertools import chain

class SubmitForm(ModelForm):
    class Meta:
        model = Post
        fields = ('title', 'link', 'text')


class CommentReplyForm(ModelForm):
    class Meta:
        model = Comment
        fields = ('post', 'parent', 'comment')


def index(request):
    posts = Post.objects.all()
    if request.GET:
        query = request.GET.get('q')
        if query:
            posts = posts.filter(
                Q(title__icontains=query) |
                Q(text__icontains=query) |
                Q(link__icontains=query) |
                Q(user__alumni__first_name__icontains=query) |
                Q(user__alumni__last_name__icontains=query) |
                Q(comment__comment__icontains=query)
            ).distinct()

            if query.isdigit():
                post1 = Post.objects.filter(
                    Q(date__year=query) |
                    Q(date__hour=query) |
                    Q(date__minute=query) |
                    Q(date__month=query) |
                    Q(date__second=query)|
                    Q(date__day=query)
                ).distinct()
                posts = chain(posts,post1)

        posts = list(posts)
        posts.sort(key=Post.score, reverse=True)
        paginator = Paginator(posts, 50)
        page = request.GET.get('p')
        try:
            posts = paginator.page(page)
        except PageNotAnInteger:
            posts = paginator.page(1)
        except EmptyPage:
            posts = paginator.page(paginator.num_pages)

        return render(request, 'posts/index.html', {'posts': posts})

    return render(request, 'posts/index.html', {'posts': posts})


def details(request, id):
    post = Post.objects.get(pk=id)
    comments = Comment.objects.filter(post=post)
    return render(request, 'posts/details.html', {'post': post, 'comments': comments})


@login_required
def submit(request):
    if request.method == 'POST':
        formset = SubmitForm(request.POST, request.FILES)
        if formset.is_valid():
            post = formset.save(commit=False)
            post.user = request.user
            post.save()
            return redirect('posts:index')
    else:
        formset = SubmitForm()
    return render(request, "posts/submit.html", {"formset": formset, })


def vote(request, id, upvote):
    post = Post.objects.get(pk=id)
    vote = Vote.objects.filter(post=post, voter=request.user)  # permits admin-mass-voting
    if vote:
        vote = vote[0]
        vote.upvote = upvote
        vote.save()
    else:
        vote = Vote(voter=request.user, post=post, upvote=upvote)
        vote.save()
    return redirect(post)


@login_required
def upvote(request, id):
    return vote(request, id, True)


@login_required
def downvote(request, id):
    return vote(request, id, False)


def comment_vote(request, post_id, node_id, upvote):
    post = Post.objects.get(pk=post_id)
    comment = Comment.objects.get(pk=node_id)
    vote = CommentVote.objects.filter(voter=request.user, comment=comment)  # permits admin-mass-voting
    print(vote)
    if vote:
        vote = vote[0]
        vote.upvote = upvote
        vote.save()
    else:
        vote = CommentVote(voter=request.user, comment=comment, upvote=upvote)
        vote.save()
    return redirect(post)


@login_required
def comment_downvote(request, post_id, node_id):
    return comment_vote(request, post_id, node_id, False)


@login_required
def comment_upvote(request, post_id, node_id):
    return comment_vote(request, post_id, node_id, True)


@login_required
def comment_reply(request, post_id, parent_id):
    if request.method == 'POST':
        formset = CommentReplyForm(request.POST)
        if formset.is_valid():
            comment = formset.save(commit=False)
            comment.author = request.user
            comment.save()
            return redirect(comment.post)
    else:
        comment = Comment()
        comment.post = Post.objects.get(pk=post_id)
        print(post_id, parent_id)
        if parent_id != 0:
            comment.parent = Comment.objects.get(pk=parent_id)
        formset = CommentReplyForm(instance=comment)
    formset.fields['post'].widget = forms.HiddenInput()
    formset.fields['parent'].widget = forms.HiddenInput()
    return render(request, "posts/comment_reply.html", {"formset": formset, })

posts/templates/posts/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head></head>
<body>
  <meta charset="UTF-8">
  <title>{% block title %}Discussion{% endblock %}</title>
  <link rel='stylesheet' href='{% static 'css/posts/style.css' %}' type='text/css' media='screen'/>
  <link rel='stylesheet' href="{% static 'css/style.css' %}" type='text/css'/>
  <script>(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)})(window,document,'script','//www.google-analytics.com/analytics.js','ga');ga('create', 'UA-30471322-4', 'dam.io');ga('send', 'pageview');</script>


  <div id="header-background">
    <header>
      <h2 class="logo"><a href="/post">Posts</a></h2>
      <nav>
        {% if user.is_authenticated %}<a href="{% url 'posts:submit' %}">Add Post</a>{% endif %}
        <span class="pull-right">
          {% if user.is_authenticated %}
          <a>Logged as {{user}}</a>
          <a href="{% url 'authentication:logout_process' %}">Logout</a>
          {% else %}
          <a href="{% url 'authentication:login_process' %}">You have to login first</a>
          {% endif %}
            <a href="{% url 'HomePage:homepage' %}">Home</a>
        </span>
      </nav>
    </header>
  </div>
  <section id="content">
    {% block content %}{% endblock %}
  </section>
</body>
</html>

posts/templates/posts/comment_reply.html
{% extends "posts/base.html" %}

{% block content %}
<form method="post" action="">
	{% csrf_token %}
    {{ formset }}
    <br/>
    <button type="submit" class="btn">Submit</button>
</form>
{% endblock %}

posts/templates/posts/details.html
{% extends "posts/base.html" %}

{% block content %}
<div>
	{% include "posts/post.html" with post=post%}
	{% if post.text %}
	<div>{{ post.text }}<div>
	{% endif %}
    {% if post.image %}
        <div class="panel-group" id="accordion_image">
            <div class="panel panel-default">
                <div id="collapseimage" class="panel-collapse collapse in">
                    <div class="container">
                        <br>
                        <img src= "{{ post.image.url }}" style = "margin-left:0%;margin-bottom:0%;" width="150" height="100">
                    </div>
                </div>
            </div>
        </div>
    {% endif %}
</div>
<h4>Comments</h4>
{% load mptt_tags %}
<div class="comments">
{% recursetree comments %}
    <div class="comment" style="margin-left: {{ node.get_level }}0px">

        <h5>
            <a href='{% url 'posts:comment_upvote' post.pk node.pk %}' class='upvote' title='upvote'>upvote</a>
    &nbsp;{{ node.score }}&nbsp;
        <a href='{% url 'posts:comment_downvote' post.pk node.pk %}' class='downvote' title='downvote'>downvote</a>

    </a>&nbsp;&nbsp;&nbsp;{{ node.author }} on {{ node.date }}</h5>
        <div>{{ node.comment|linebreaks }}</div>
        {% if user.is_authenticated %}<a href="{% url 'posts:comment_reply' post.pk node.pk %}">Reply</a>{% endif %}
    </div>
    {% if not node.is_leaf_node %}
        {{ children }}
    {% endif %}
{% endrecursetree %}
{% if user.is_authenticated %}
<br/>
<a href="{% url 'posts:comment_reply' post.pk 0 %}"> - New thread </a>
</div>
{% endif %}

{% endblock %}

posts/templates/posts/index.html
{% extends "posts/base.html" %}

{% block content %}
    <div class="container" >
        <form method = 'GET' action = "">
            <input type = "text" name = "q" placeholder="searchcommunity" value = "{{ request.GET.q }}"/>
            <input type = "submit" value = "search" />
        </form>
    </div>
    {% for post in posts %}
    <ol class="posts">
    <li >{% include "posts/post.html" with post=post %}</li>
    </ol>
    {% endfor %}

    <div class="pagination">
            {% if posts.has_previous %}
                <a href="?p={{ posts.previous_page_number }}">Previous</a>
            {% endif %}
            {% if posts.has_next %}
                <a class="next" href="?p={{ posts.next_page_number }}">Next</a>
            {% endif %}
    </div>
{% endblock %}

posts/templates/posts/post.html
{% load humanize %}

<span class="post">
	<a href='{% url 'posts:upvote' post.pk %}' class='upvote' title='upvote' {% if not user.is_authenticated %} onclick="alert('You need to be logged to vote')" {% endif %}>vote up</a>
	{% if post.link %}
	<a class="link" href="{{ post.link }}">{{ post.title }}</a><span class="comhead"> ({{post.get_domain}}) </span>
	{% else %}
	<a class="link" href="{% url 'posts:details' post.pk %}">{{ post.title }}</a>
	{% endif %}
	<span class="score">
	{% with total=post.score %}
		{{ total }} point{{ total|pluralize }}
	{% endwith %}

	</span> by {{ post.user }} {{ post.date}}  | <a class="comments" href="{% url 'posts:details' post.pk %}">
	{% with total=post.comments_count %}
		{{ total }} comment{{ total|pluralize }}
	{% endwith %}</a>
</span>

posts/templates/posts/submit.html
{% extends "posts/base.html" %}

{% block content %}
<form method="post" action="">
	{% csrf_token %}
    {{ formset }}
    <br/>
    <button type="submit" class="btn">Submit</button>
</form>
{% endblock %}